MvcWebUI/Models/CartListViewModel.cs
using Entities.Concrete;
using Entities.DomainModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class CartListViewModel
    {
        public Cart Cart { get; set; }

    }
}

MvcWebUI/Models/CategoryListViewModel.cs
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int currentCategory { get;  set; }
    }
}

MvcWebUI/Models/ErrorViewModel.cs
using System;

namespace MvcWebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcWebUI/Models/ProductListViewModel.cs
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }
    }
}

MvcWebUI/Models/ShippingDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class ShippingDetail
    {
       // [Required(ErrorMessage ="İsim zorunludur.")]
        public string FirstName { get; set; }
       // [Required(ErrorMessage = "Soyisim zorunludur.")]
        public string LastName { get; set; }
       // [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string City { get; set; }
       // [MinLength(10,ErrorMessage ="Minumum 10 karakter olmalı.")]
        public string Address { get; set; }
       // [Range(18,65)]
        public int Age { get; set; }
    }
}

MvcWebUI/Models/ShippingDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.Models
{
    public class ShippingDetailsViewModel
    {
        public ShippingDetail ShippingDetail { get; set; }
    }
}

MvcWebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Helpers;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class CartController : Controller
    {
        private ICartService _cartService;
        private ICartSessionHelper _cartSessionHelper;
        private IProductService _productService;
        public CartController(ICartService cartService, ICartSessionHelper cartSessionHelper, IProductService productService)
        {
            _cartService = cartService;
            _cartSessionHelper = cartSessionHelper;
            _productService = productService;

        }
        //sepete ekle butonu için

        public IActionResult AddToCart(int productid)
        {
            //öncelikle idsi verilen ürünü veritabanından cekmemiz gerekiyor
            Product product = _productService.GetById(productid);
            //sonra sessiondan sepeti çekmem gerekiyor öünkü oraya eklicem
            var cart = _cartSessionHelper.GetCart(key: "cart");
            //sepete ürünü eklemem gerekiyor 
            _cartService.AddToCart(cart, product);
            //sepeti sessiona geri eklememiz gerekiyor.
            _cartSessionHelper.SetCart(key: "cart", cart);
            //ProductContorllerdaki index aksiyonuna gönder.
            TempData.Add("message", product.ProductName + " sepette eklendi!");
            return RedirectToAction("Index", controllerName: "Product");
        }
        public IActionResult RemoveFromCart(int productid)
        {
            Product product = _productService.GetById(productid);
            var cart = _cartSessionHelper.GetCart(key: "cart");
            _cartService.RemoveFromCart(cart, productid);
            _cartSessionHelper.SetCart(key: "cart", cart);
            TempData.Add("message", product.ProductName + " sepetten silindi!");
            return RedirectToAction("Index", controllerName: "Cart");
        }
        public IActionResult Index()
        {
            var model = new CartListViewModel
            {
                Cart = _cartSessionHelper.GetCart(key: "cart")
            };
            return View(model);

        }
        public IActionResult Complete()
        {
            var model = new ShippingDetailsViewModel
            {
                ShippingDetail = new ShippingDetail()
            };
            return View(model);

        }
        [HttpPost]
        public IActionResult Complete(ShippingDetail shippingDetail)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TempData.Add("message", "Siparişiniz başarıyla tamamlandı!");
            _cartSessionHelper.Clear();
            return RedirectToAction("Index", controllerName: "Cart");
        }
    }
}

MvcWebUI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class CategoryController : Controller
    {

        private ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IActionResult Index()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll()
            };
            return View(model);
        }
    }
}

MvcWebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcWebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using MvcWebUI.Models;

namespace MvcWebUI.Controllers
{
    public class ProductController : Controller
    {

        private IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Index(int category) //int oldugundan yoksa 0 kabul eder.
        {

            var model = new ProductListViewModel
            {
                Products =category>0?_productService.GetByCategory(category):_productService.GetAll()
            };
            return View(model);
        }
    }
}

MvcWebUI/ViewComponents/CategoryListViewComponent.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using MvcWebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcWebUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public ViewViewComponentResult Invoke()
        {
            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                currentCategory = Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

MvcWebUI/Views/Cart/Complete.cshtml
@model ShippingDetailsViewModel

    <form asp-controller="Cart" asp-action="Complete" method="post">
        <div class="form-group">
            <label asp-for="ShippingDetail.FirstName">Ad</label>
            <input asp-for="ShippingDetail.FirstName" class="form-control" placeholder="Müşteri Adı" />
           <span asp-validation-for="ShippingDetail.FirstName" ></span>
        </div>
        <div class="form-group">
            <label asp-for="ShippingDetail.LastName">Soyad</label>
            <input asp-for="ShippingDetail.LastName" class="form-control" placeholder="Müşteri Soyadı" />
            <span asp-validation-for="ShippingDetail.LastName"></span>
        </div>
        <div class="form-group">
            <label asp-for="ShippingDetail.Email">E-Mail</label>
            <input asp-for="ShippingDetail.Email" class="form-control" placeholder="Müşteri Email" />
            <span asp-validation-for="ShippingDetail.Email"></span>
        </div>
        <div class="form-group">
            <label asp-for="ShippingDetail.Age">Yaş</label>
            <input asp-for="ShippingDetail.Age" class="form-control" placeholder="Müşteri Yaşı" />
            <span asp-validation-for="ShippingDetail.Age"></span>
        </div>
        <div class="form-group">
            <label asp-for="ShippingDetail.City">Ad</label>
            <input asp-for="ShippingDetail.City" class="form-control" placeholder="Müşteri Şehir" />
            <span asp-validation-for="ShippingDetail.City"></span>
        </div>
        <div class="form-group">
            <label asp-for="ShippingDetail.Address">Adres</label>
            <input asp-for="ShippingDetail.Address" class="form-control" placeholder="Müşteri Adres" />
            <span asp-validation-for="ShippingDetail.Address"></span>
        </div>
        <input type="submit" value="Kaydet" class="btn btn-success btn-group-sm" />
        
    </form>

MvcWebUI/Views/Cart/Index.cshtml
@model CartListViewModel


<h2>Sepetiniz</h2>
@if (Model.Cart.cartLines.Count == 0)
{
    <h2 class="badge badge-danger">Sepetiniz boş</h2>
}
else
{

<table class="table table-responsive">

    <thead>
        <tr>
            <th>Id</th>
            <th>Ürün Adı</th>
            <th>Açıklama</th>
            <th>Fiyat</th>
            <th>Stok Adedi</th>
            <th>Satış Adedi</th>
        </tr>
    </thead>

    @foreach (var cartLine in Model.Cart.cartLines)
    {
        <tbody>
            <tr>
                <td>@cartLine.product.ProductID</td>
                <td>@cartLine.product.ProductName</td>
                <td>@cartLine.product.QuantityPerUnit</td>
                <td>@cartLine.product.UnitPrice</td>
                <td>@cartLine.product.UnitsInStock</td>
                <td>@cartLine.Quantity</td>
                <td><a class="btn btn-sm btn-danger" asp-controller="Cart" asp-action="RemoveFromCart" asp-route-productid="@cartLine.product.ProductID">Sil</a></td>
            </tr>

        </tbody>
    }
    <tr>
        <td><a class="btn btn-sm btn-success" asp-controller="Cart" asp-action="Complete" >Sepeti Tamamla</a></td>
        </tr>
</table>

}

MvcWebUI/Views/Category/Index.cshtml
@model CategoryListViewModel
@{
    ViewBag.title = "title";
    Layout = "_Layout";
}

<h2>Category Listesi</h2>

<table class="table table-responsive">
    @foreach (var category in Model.Categories)
    {
    <tr>
        <td>@category.CategoryID</td>
        <td>@category.CategoryName</td>

    </tr>
    }
</table>

MvcWebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcWebUI/Views/Product/Index.cshtml
@model ProductListViewModel
@{
    ViewBag.title = "title";
    Layout = "_Layout";
}

<h2>Ürünler</h2>

<table class="table table-responsive">
@foreach(var product in Model.Products)
{
    <tr>
        <td>@product.ProductID</td>
        <td>@product.ProductName</td>
        <td>@product.QuantityPerUnit</td>
        <td>@product.UnitPrice</td>
        <td>@product.UnitsInStock</td>
        <td><a class="btn btn-sm btn-success" asp-controller="Cart" asp-action="AddToCart" asp-route-productid="@product.ProductID">Sepete Ekle</a></td>
    </tr>
}
</table>

MvcWebUI/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel


<h2>Kategoriler</h2>

<div class="list-group">
   
<a href="/product/index" class="list-group-item">Tüm Ürünler</a>
 
     @foreach (var category in Model.Categories)
     {
         var css = "list-group-item";
         if(category.CategoryID==Model.currentCategory)
         {
             css += " active";
         }
         <a href="/product/index?category=@category.CategoryID" class="@css">@category.CategoryName</a>

    }
</div>

MvcWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcWebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcWebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Sepete Git</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                @if (TempData["message"] != null)
                {
                <div class="alert alert-primary">
                    @TempData["message"]
                </div>
                }
            </div>
            <div class="row">
                <div class="col-3">
                    @await Component.InvokeAsync("CategoryList")
                </div>
                <div class="col-9">@RenderBody()</div>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MvcWebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>